name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: docs
          PUBLISH_BRANCH: main
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
